title: "Blog Title"
author: "Blog Author"
description: "Really cool blog about ... something"
more: "read more »"
url: "https://niklasbuschmann.github.io"
baseurl: "/contrast" # comment out if in root directory

comments:
  disqus: "niklasbuschmann"
#  isso: "comments.mysite.org"

style:
  body: 'white'
  margin: 0%
  padding: 20%
  nav: "#222"
  articles: 'stripe' # 'light' 'dark' and 'stripe' possible
  uppercase: true

links:
  - github: "https://github.com/me/"
  - reddit: "https://www.reddit.com/user/me/"
  - twitter: "https://twitter.com/me/"
  - facebook: "https://www.facebook.com/me"
  - google-plus: "https://plus.google.com/+me"
  - youtube: "https://www.youtube.com/user/me"
  - tumblr: "http://me.tumblr.com/"
  - steam: "http://steamcommunity.com/id/me/"

paginate: 10
excerpt_separator: "\n\n\n" # excerpt ends after two blank lines
defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
gems: [jekyll-feed] # include feed plugin (supported by gh-pages)
